name: Run Asura Scrape
on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches: ["master"]
jobs:
  cron:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npm i
      - run: |
          cd services
          node mangaScrape.js
